apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3-sample-app
spec:
  selector:
    matchLabels:
      app: web3-sample-app
  template:
    metadata:
      labels:
        app: web3-sample-app
    spec:
      containers:
        - name: web3-sample-app
          image: ghcr.io/qleet/web3-sample-app:v0.0.7
          env:
            - name: PORT
              value: "8080"
            - name: VITE_RPC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: web3-sample-app-config
                  key: rpc.endpoint
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1m"
              memory: "6Mi"
            limits:
              cpu: "3m"
              memory: "8Mi"
          imagePullSecret:
            - name: ghcr-login-secret
      restartPolicy: Always