name: web3-sample-app CI

on:
  push:
  pull_request:

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.6.0

    - name: Cache Docker layers
      uses: actions/cache@v3.2.6
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Convert owner to lower case
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Login to image repository
      if: github.ref_type == 'tag'
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ghcr.io/${{ env.OWNER_LC }}/web3-sample-app
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}

    - name: Build and push
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.ref_type == 'tag' }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}